### ISSUE TITLE
Different definitions of face_joint_idx in src/guofeats/skeleton.py and src/guofeats/motion_representation.py

### ISSUE THREAD

**Issue by KikiLovesPomelo** [Mathux/TMR#13]
Hi Mathux, thanks for your excellent work on this motion retrival task, it's very impressive! 
I have a question about the face_joint_idx variabal.

You commented that on line 77 in this [src/guofeats/common/skeleton.py#L82-L86](https://github.com/Mathux/TMR/blob/master/src/guofeats/common/skeleton.py#L82-L86),

`"face_joint_idx should follow the order of right hip, left hip, right shoulder, left shoulder" `

but on line 82, you wrote `l_hip, r_hip, sdr_r, sdr_l = face_joint_idx`

However, on line 101 in [src/guofeats/motion_representation.py#L239-L242](https://github.com/Mathux/TMR/blob/master/src/guofeats/motion_representation.py#L239-L242) you just wrote 
`r_hip, l_hip, sdr_r, sdr_l = face_joint_idx` 

According to the code 
`face_joint_idx` = [2, 1, 17, 14] in [src/guofeats/motion_representation.py#L351-L352](https://github.com/Mathux/TMR/blob/master/src/guofeats/motion_representation.py#L351-L352) , 
it seems  `l_hip, r_hip, sdr_r, sdr_l = face_joint_idx` in src/guofeats/common/skeleton might be wrong.

I want to know what makes this difference.
![image](https://github.com/Mathux/TMR/assets/26195509/57a0c2ee-4385-4df1-9b5f-3a8137b14ec1)

**Comment by Mathux** [comment]
Hello @KikiLovesPomelo 

Thanks for your issue. This problem comes from the original implementation of HumanML3D, which we need to use to have comparable results with other methods. I only "adapted" their code in this repo without fixing any bugs (to be comparable).

The problem originally appear here:
https://github.com/EricGuo5513/HumanML3D/blob/6b72fcda6c4fb90be69efd784942bf08be2d51e1/common/skeleton.py#L58
https://github.com/EricGuo5513/HumanML3D/blame/6b72fcda6c4fb90be69efd784942bf08be2d51e1/motion_representation.ipynb#L85

And the latest issue mentioning this problem is there: https://github.com/EricGuo5513/HumanML3D/issues/119.

Actually, there are a lot more issues with this dataset. I would recommend using only the text annotations and use motions directly from AMASS. You can check this [repo](https://github.com/Mathux/AMASS-Annotation-Unifier) to have an easier start.

**Comment by KikiLovesPomelo** [comment]
Thank you for your quick reply!! :)
